version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--storage.tsdb.retention.time=1m'
      - '--storage.tsdb.retention.size=100MB'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  node-exporter:
    image: prom/node-exporter
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave
    deploy:
      mode: global
    ports:
      - target: 9100
        published: 9100
        mode: host
    labels:
      - "monitoring=true"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana-data:/var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: "10"
 
  traefik:
    image: traefik:v2.10
    command:
      - --providers.docker.swarmmode=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --entrypoints.api.address=:8000
    ports:
      - "80:80"
      - "8080:8080"  # Traefik 대시보드
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1

  whoami:
    image: containous/whoami
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.local`)"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.entrypoints=web"

  metrics-api:
    build: ./metrics-api
    image: metrics-api:latest 
    container_name: metrics-api
    working_dir: /app
    volumes:
      - ./metrics-api:/app
    ports:
      - "8000:8000"
    depends_on:
      - prometheus

# /etc/hosts에 다음 줄 추가 필요:
# 127.0.0.1 whoami.local

volumes:
   grafana-data: {}

configs:
  prometheus_config:
    file: ./prometheus.yml
